### ISSUE TITLE
Concat relation fields

### ISSUE THREAD

**Issue by jp-gauthier** [akki-io/laravel-nova-search#4]
Hi there,

interesting package, thanks!

I have a feature request.. here's my use case :

- A `post` is related to a `user`
- I want to search `post.title`, `post.content` but also a concat of `post.user.firstname`+`post.user.lastname`

Is there any way to search concatenated fields of a relation ?

**Comment by akki-io** [comment]
Hey @jp-gauthier, Currently the package does not support concatenated search on a relation. That might be a nice thing to add to the package. I will try to add this as soon as I get some time, most probably this weekend. If you want feel free to create a PR for the same.

**Comment by jp-gauthier** [comment]
Hello @akki-io, excellent, really appreciated! 
I'll let you add this by yourself, so keep me in the loop.
Thanks again.
